# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reporting_pb2 as reporting__pb2


class ShipsListStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReturnShips = channel.unary_unary(
                '/protoblog.ShipsList/ReturnShips',
                request_serializer=reporting__pb2.CoordinatesRequest.SerializeToString,
                response_deserializer=reporting__pb2.ShipsResponse.FromString,
                )


class ShipsListServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReturnShips(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShipsListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReturnShips': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnShips,
                    request_deserializer=reporting__pb2.CoordinatesRequest.FromString,
                    response_serializer=reporting__pb2.ShipsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protoblog.ShipsList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShipsList(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReturnShips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protoblog.ShipsList/ReturnShips',
            reporting__pb2.CoordinatesRequest.SerializeToString,
            reporting__pb2.ShipsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
