# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reporting.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freporting.proto\x12\tprotoblog\"=\n\x08Officers\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\xdf\x01\n\x05Ships\x12,\n\talignment\x18\x01 \x01(\x0e\x32\x19.protoblog.AlignmentState\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\x06\x63lasss\x18\x03 \x01(\x0e\x32\x14.protoblog.ClassName\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\'\n\x05\x61rmed\x18\x06 \x01(\x0e\x32\x18.protoblog.DumbProtoBool\x12(\n\x0boficer_crew\x18\x07 \x03(\x0b\x32\x13.protoblog.Officers\"{\n\x12\x43oordinatesRequest\x12\x10\n\x08\x61sc_hour\x18\x01 \x01(\x02\x12\x0f\n\x07\x61sc_min\x18\x02 \x01(\x02\x12\x0f\n\x07\x61sc_sec\x18\x03 \x01(\x02\x12\x0f\n\x07\x64\x65\x63_fir\x18\x04 \x01(\x02\x12\x0f\n\x07\x64\x65\x63_sec\x18\x05 \x01(\x02\x12\x0f\n\x07\x64\x65\x63_thi\x18\x06 \x01(\x02\"/\n\rShipsResponse\x12\x1e\n\x04ship\x18\x01 \x03(\x0b\x32\x10.protoblog.Ships*2\n\x0e\x41lignmentState\x12\x0b\n\x07Problem\x10\x00\x12\x08\n\x04\x41lly\x10\x01\x12\t\n\x05\x45nemy\x10\x02*o\n\tClassName\x12\r\n\tProblem_2\x10\x00\x12\x0c\n\x08\x43orvette\x10\x01\x12\x0b\n\x07\x46rigate\x10\x02\x12\x0b\n\x07\x43ruiser\x10\x03\x12\r\n\tDestroyer\x10\x04\x12\x0b\n\x07\x43\x61rrier\x10\x05\x12\x0f\n\x0b\x44readnought\x10\x06*2\n\rDumbProtoBool\x12\x0c\n\x08Problem3\x10\x00\x12\x08\n\x04True\x10\x01\x12\t\n\x05\x46\x61lse\x10\x02\x32S\n\tShipsList\x12\x46\n\x0bReturnShips\x12\x1d.protoblog.CoordinatesRequest\x1a\x18.protoblog.ShipsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reporting_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ALIGNMENTSTATE']._serialized_start=493
  _globals['_ALIGNMENTSTATE']._serialized_end=543
  _globals['_CLASSNAME']._serialized_start=545
  _globals['_CLASSNAME']._serialized_end=656
  _globals['_DUMBPROTOBOOL']._serialized_start=658
  _globals['_DUMBPROTOBOOL']._serialized_end=708
  _globals['_OFFICERS']._serialized_start=30
  _globals['_OFFICERS']._serialized_end=91
  _globals['_SHIPS']._serialized_start=94
  _globals['_SHIPS']._serialized_end=317
  _globals['_COORDINATESREQUEST']._serialized_start=319
  _globals['_COORDINATESREQUEST']._serialized_end=442
  _globals['_SHIPSRESPONSE']._serialized_start=444
  _globals['_SHIPSRESPONSE']._serialized_end=491
  _globals['_SHIPSLIST']._serialized_start=710
  _globals['_SHIPSLIST']._serialized_end=793
# @@protoc_insertion_point(module_scope)
